version: '3.8'
services:
  web:
    build: .
    container_name: anywhere_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
